### ISSUE TITLE
[regression] "socket hang up"

### ISSUE THREAD

**Issue by bradvogel** [rapid7/le_node#135]
We upgraded le_node from 1.3.0 to 1.6.5 (with no other changes) and our node process started crashing every 4 hours with "socket hang up" - with no stack trace unfortunately. We then downgraded le_node back to 1.3.0 and the error went away. So we're 100% sure it's le_node.

This is how we're using le_node:

```
var Logger = require('le_node');
var logger = new Logger({
  token: token,
  bufferSize: 400000,
  secure: true
});

logger.on('error', function(e) {
  console.error(e); // We aren't seeing this in logs.
});

logger.log('info', {
  message: 'message...'
});
```

Given that we're handling the 'error' event, it would seem as though it shouldn't crash. I didn't see in the [full diff](https://github.com/rapid7/le_node/compare/1.3.0...1.6.5?w=1) that immediately jumped out possible regression caused by an unhandled 'error' event.

Is this a known issue? We can try to incrementally upgrade to figure out the exact version that broke, but that will take some time. I was hoping someone here would be able to identify the regression.

**Comment by stopal-r7** [comment]
@bradvogel thanks for the feedback. could you share some logs? is it happening every 4 hours sharp?

**Comment by bradvogel** [comment]
Here's the raw stack trace. Unfortunately I don't have any more detail than that. It happened on average every 4 hours, but not sharp. More often at peak hours.

```
Error: socket hang up
  File "_tls_wrap.js", line 1049, in TLSSocket.onHangUp
  File "events.js", line 260, in TLSSocket.g
  File "events.js", line 72, in emitNone
  File "events.js", line 166, in TLSSocket.emit
  File "_stream_readable.js", line 913, in endReadableNT
  File "node.js", line 442, in nextTickCallbackWith2Args
  File "node.js", line 397, in process._tickDomainCallback
```

**Comment by RodH257** [comment]
I'm getting the same issue here, catching it in my global unhandled exception handler. Stack trace isn't very useful, and it crashes my process. I'll try rolling back to 1.3.0.

**Comment by stopal-r7** [comment]
@RodH257 @bradvogel, can you run logger in debug mode and share the logs just before "socket hang up" occurs. That could really help to troubleshoot the issue.

**Comment by perhallstroem** [comment]
Getting the same thing (going from 1.3.2 to 1.6.7). With "longjohn" (which attempts to capture slightly more useful stack traces), I am getting the following trace when the process crashes:

`Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
---------------------------------------------
    at fireErrorCallbacks (net.js:465:15)
    at TLSSocket.Socket._destroy (net.js:472:5)
    at TLSSocket.Socket.destroy (net.js:519:8)
    at TLSSocket.onHangUp (_tls_wrap.js:1094:14)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
---------------------------------------------
    at Object.exports.connect (_tls_wrap.js:1097:10)
    at EventEmitter.initialize (/application/node_modules/le_node/src/logger.js:151:34)
    at attempt (/application/node_modules/reconnect-core/index.js:44:34)
    at EventEmitter.emitter.connect.emitter.listen (/application/node_modules/reconnect-core/index.js:110:7)
    at /application/node_modules/le_node/src/logger.js:420:-15
    at Promise.F (/application/node_modules/core-js/library/modules/_export.js:35:28)
    at Logger.get (/application/node_modules/le_node/src/logger.js:379:-17)
    at Logger._write (/application/node_modules/le_node/src/logger.js:184:-8)
    at doWrite (_stream_writable.js:307:12)
`

Have since gone back to 1.3.2, and have not seen any more of these problems.

**Comment by bradvogel** [comment]
Sounds like @perhallstroem can reproduce it better than I can. Unfortunately it happens to me only rarely, and in production where I can't debug it.

**Comment by stopal-r7** [comment]
I am now investigating this issue and try to reproduce the bug(a tough one to reproduce). I am guessing that this was introduced with version 1.6.5. Can you try to use 1.6.4 and check if this happens?
