### ISSUE TITLE
Winston log added error undefined 

### ISSUE THREAD

**Issue by gobiltd** [rapid7/le_node#95]
/root/codebase/Driveboy/PerformanceTesting/Dispatcher/lib/log/node_modules/winston/lib/winston/logger.js:475
  var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: undefined is not a function
    at Logger.add (/root/codebase/Driveboy/PerformanceTesting/Dispatcher/lib/log/node_modules/winston/lib/winston/logger.js:475:41)
    at Object.winston.(anonymous function) [as add] (/root/codebase/Driveboy/PerformanceTesting/Dispatcher/lib/log/node_modules/winston/lib/winston.js:87:34)
    at Object.<anonymous> (/root/codebase/Driveboy/PerformanceTesting/Dispatcher/lib/log/index.js:3:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/codebase/Driveboy/PerformanceTesting/Dispatcher/servicehandler.js:3:11)

**Comment by bathos** [comment]
I'm not sure what the context is here, so it's not clear how this related to le_node given that stacktrace is about winston. There are a few similar looking issues active on the winston board right now, e.g. https://github.com/winstonjs/winston/issues/674

**Comment by gearoidof-r7** [comment]
This is a winston issue, not us.
